Remove ComputeFramesClassWriter used to fix asm issues due to causes NoClassDefFoundError: net/minecraft/client/gui/inventory/GuiContainer, and seems like not needed anymore in modern GTNH